runtime: python27
api_version: 1
threadsafe: yes
service: sql

handlers:
- url: /
  script: main.app

libraries:
- name: MySQLdb
  version: "latest"

env_variables:
    CLOUDSQL_CONNECTION_NAME: db
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: password
